name: Generate Metrics

on:
  schedule: 
    - cron: "0 */10 * * *"
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  github-metrics:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
      - name: Youtube Music - Random track from playlist
        uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          filename: metrics.plugin.music.svg
          base: ""
          plugin_music: yes
          plugin_music_provider: youtube
          plugin_music_mode: playlist
          plugin_music_token: ${{ secrets.YOUTUBE_MUSIC_TOKENS }}
          plugin_music_playlist: >-
            https://music.youtube.com/playlist?list=PLohZUqpdwH_kXHCyLBbAcsRX3_inWjqal

