name: Generate Metrics

on:
  schedule: 
    - cron: "0 */10 * * *"
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  github-metrics:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
