name: Generate Metrics

on:
  schedule: 
    - cron: "0 */10 * * *"
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  github-metrics:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
      - name: Comment reactions
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.reactions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: percentage
